name: "test build"
on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.8.0
      with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-23.11
        extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
    - run: git clone ssh://git@github.com/op-energy-foundation/op-energy-dev-instance.git ../op-energy-dev-instance --recursive
    # copy content of frontend repo into the frontend overlay submodule location
    - run: rm -rf ../op-energy-dev-instance/overlays/op-energy-frontend/* && cp -r $(pwd)/* ../op-energy-dev-instance/overlays/op-energy-frontend/
    - run: echo \"ci-host\" > ../op-energy-dev-instance/local_hostname.nix
    # ci-tests.nix should be on the same level as op-energy-development
    - run: cp ci-tests.nix ../
    # now actually run the builds and tests with passing git commit hash as an argument
    - run: cd ../ && nix-build ci-tests.nix --argstr GIT_COMMIT_HASH $( echo ${{github.sha}} | cut -c 1-8 )

